go-gitea/git

repo.go
Just a simple addition of the --rebase flag for git pull.
=> Add Rebase option to Pull

tree_entry.go
This pull request remove usage of _sleep_ function who slow down git repos browsing (Issue #18).
Moved from https://github.com/gogits/git-module/pull/24
=> Sleep induced slowness in gogits

tree_entry.go
Currently, the number of goroutine is hard-coded to 10. It is not efficient, by exemple, with 2 core CPU or with 16 core- CPU.
This pull request add ability to set the maximum number of goroutine allowed on the function `GetCommitsInfo` (issue #25). If the given number is equal of lower than 0, the function `runtime.NumCPU()` will be used.
Later, if this PR is accepted, user will be able to set this max number of goroutine directly from Gitea `app.ini` configuration file.
=> Custom max number of goroutine

blob.go, command.go, commit.go, commit_archive.go, error.go, git.go, hook.go, repo.go, repo_branch.go, repo_commit.go, repo_hook.go, repo_object.go, repo_pull.go, repo_tag.go, repo_tree.go, sha1.go, submodule.go, tag.go, tree.go, tree_blob.go, tree_entry.go, utlis.go
This PR will fix the golint errors. But we need set the golint minimal confidence to 0.9 although the default confidence is 0.8, because there are some errors could not be resolved currently. If you have any idea, please send a new PR to fix it.
```
commit.go:42:35: exported method ParentID returns unexported type git.sha1, which can be annoying to use
commit.go:211:35: exported method GetSubModules returns unexported type *git.objectCache, which can be annoying to use
sha1.go:59:23: exported func MustID returns unexported type git.sha1, which can be annoying to use
sha1.go:68:23: exported func NewID returns unexported type git.sha1, which can be annoying to use
sha1.go:76:33: exported func MustIDFromString returns unexported type git.sha1, which can be annoying to use
sha1.go:82:33: …
```
=> golint fixed

command.go
Since go-gitea/gitea#122 depends on this, I sent it.
=> added global git command args support

tree_entry.go
* rename utlis.go to utils.go
* TreeEntry IsLink function
cherry-pick from gogits/git-module#20, this is depened by go-gitea/gitea#445
=> Check if files are a symlink (#20)

tree_entry.go
Simple implementation of [ Folder Jumping](https://github.com/blog/1877-folder-jumping)
Comes with this [PR](https://github.com/go-gitea/gitea/pull/511)
=> Implementation of Folder Jumping

commit.go, repo_commit.go
As requested for this : https://github.com/go-gitea/gitea/pull/813
=> Add ability to search for commit messages in all the branches

repo_blame.go
Adding git-blame implementation. Prepare for git blame [feature](https://github.com/go-gitea/gitea/issues/747) implementation.
=> Adding git blame

commit.go, repo_commit.go
based on : https://github.com/git/git/blob/3bc53220cb2dcf709f7a027a3f526befd021d858/commit.c#L1128
I have to do further testing to determine if the struct CommitGPGSignature could not be replace by a simple string representing directly CommitGPGSignature.Signature. Since payload can maybe re-created from the rest of data in Commit struct.
If we don't care about duplicate of data at this stage it will simplify treatment after since payload and signature (+ public key from keystore in gitea) is only needed to verify the signed commit. https://github.com/git/git/blob/2cc2e70264e0fcba04f9ef791d144bbc8b501206/gpg-interface.c#L204
=> Add GPG payload to commit information if present

repo_commit.go
when viewing a file's history, e.g. `https://git.myserver.example/myuser/myrepo/commits/master/subdir/file`, the log does not follow file renames. This patch should change that.
=> use --follow on file history to show log across renames

repo.go
GetRepoSize() implementation for use with https://github.com/go-gitea/gitea/pull/39
=> Add GetRepoSize implemented using count-objects

command.go
For https://github.com/go-gitea/gitea/issues/1453 and probably https://github.com/go-gitea/gitea/issues/1398.
=> Use exec.CommandContext for timeout control

command_test.go
For #41 
Caveats:
1. The tests are only run when -race enabled
2. The test for 'no timeout happening scenario' takes long time to run, about 13 seconds for 1000 repetitions on my laptop.
3. The testing loops might not be necessary. Under the -race enabled, the race get positive in the first round for TestRunInDirTimeoutPipelineAlwaysTimeout.
=> Add tests for RunInDirTimeoutPipeline

git.go
Panic during init() if Git version is < GitVersionRequired.
I have set the min version to 1.7.10 as required by SetDefaultBranch (https://github.com/go-gitea/git/blob/master/repo_branch.go#L58). I'm not sure why 1.7.10 is required for SetDefaultBranch, symbolic-ref has been in there for a while https://git-scm.com/docs/git-symbolic-ref/1.4.4.
Ref: https://github.com/go-gitea/gitea/issues/1133
=> Panic if Git version is < GitVersionRequired

git.go
see https://git-scm.com/docs/git-log/1.8.1.6 and this will fix go-gitea/gitea#1133
=> ask git version from 1.7.10 to 1.8.1.6 since git log command needs

repo.go
Get time for latest commit in repo across all branches. To be used in https://github.com/go-gitea/gitea/issues/1329
=> Add GetLatestCommitTime

repo.go
=> add options force to push

command.go, command_test.go
For #42 and #41 
Sanitizing the error handling a little bit, now it looks nicer.
=> Rectify error handling

repo_branch.go
This pull request enables the git module to handle bare (empty) repositories when getting all branches of a repository. This failed previously, because the command to retrieve the branches `git show-ref --heads` exited with return code `1` which resulted in a non-nil error.
The new implementation uses `git for-each-ref` to iterate over all branches and outputs nothing in case the repository is bare while using a return code of `0`. As the output format changed (and now is much simpler), the parsing of that output had to be changed as well.
This is in preparation of a coming pull request to gitea itself to [gracefully handle bare repositories on various API operations](https://github.com/cybe/gitea/commit/9f0e75a70b4415bd5be0a49586996d34961dfa7d) instead of throwing HTTP-500 errors.
=> Return empty list of branches if repository is bare.

.gitignore, Makefile, tree_entry.go, tree_entry_test.go
A faster implementation of `GetCommitsInfo`, addresses https://github.com/go-gitea/gitea/issues/491 and https://github.com/go-gitea/gitea/issues/502.
The previous implementation made a call to `git log` for each entry, each of which required scanning through the commit history. This new implementation instead makes a single call to `git log`. This is faster, because it involves scanning the commit history only once.
__BENCHMARK RESULTS__:
Shoutout to @sapk for the benchmark tests he wrote (#54), which I have stolen here.
Old implementation:
```
BenchmarkEntries_GetCommitsInfo/gitea-4         	     200	  70670229 ns/op
BenchmarkEntries_GetCommitsInfo/manyfiles-4     	       1	35907609610 ns/op
BenchmarkEntries_GetCommitsInfo/moby-4          	      50	 204585469 ns/op …
```
=> Faster commit lookup

blob_test.go, tree_entry_test.go
Use `b.Fatal` instead of `panic` in benchmark tests. Also check for previously-unchecked errors in `blob_test.go`
=> Use b.Fatal in benchmark tests

command.go
Check and return the error returned by `cmd.Wait()`, instead of quietly logging and ignoring.
Ignoring this error, because the subsequent call to `ctx.Err()` may return `nil` even if `cmd.Wait()` returned an actual error. For instance, `git show-ref --verify <non-existent-branch>` will fail with a exit code of 128, and `cmd.Wait()` will return an error, but `cmd.Wait()` will return `nil`.
=> Return error from cmd.Wait()

tree_entry.go
Fix bug from #53. Hard-coding `HEAD` breaks things when you're not on the master branch.
Fixes https://github.com/go-gitea/gitea/issues/1836
=> Fix bug in GetCommitInfos

repo_tag.go
The previous implementation of `GetTagInfos()` would break when commit messages contained closing parentheses (previous line 125), and would not account for when one commit could have several tags.
=> Fix parsing bug in GetTagInfos

tree_entry.go
Use `os.PathSeparator` instead of `'/'`. Fixes https://github.com/go-gitea/gitea/issues/1836 (confirmation pending)
=> Use cross-platform path separator

tree_entry.go
The filenames in the output of `git log` command may contain escaped characters in quotes (e.g. for files whose name contain backslashes):
```
13d136320bad8b0318c2476a392fafb11b0bcf13
"content\\G44870\\ῥῆμα.md"
```
`getCommitInfos` previously did not for account this; with these changes it does.
=> Fix escaped char bug in getCommitInfos

tree_entry.go
Fixes https://github.com/go-gitea/gitea/issues/1933. Also rename variable to avoid collision with `path` package, and update stale comment.
=> Fix Windows path bug in GetCommitInfos

tree_entry.go
Fix unchecked error bug in helper function for `GetCommitsInfo(..)`
=> Check unchecked error

tree_entry.go
Reverts #53 (and several subsequent bug fixes).
There are problems with the new implementation of `GetCommitsInfo(..)` that was introduced in #53 (see #72). For the sake of having a bug-free 1.2.0 release, we should revert to the old, slower implementation for now.
I do still hope to eventually salvage the faster implementation.
=> Revert to old implementation of GetCommitsInfo

Makefile
-not is a GNU extension and not all find(8) implementations
support it. It's just an alias for ! which is POSIX compliant.
=> Use POSIX complaint ! operator in find

commit.go, repo_branch.go, repo_commit.go
Since the required git version is set to `1.8.1.6` we can remove some version checks and fallbacks.
=> Remove unnecessary version checks

.drone.yml, commit_test.go, docker/ci/Dockerfile-git-1.7, docker/ci/Makefile, git.go, repo_test.go
Debian old old (very old) distribution (6.0 aka Squeeze)
ships version 1.7.10.4.
The version requirement was raised in #46 supposedly for the
need of "symbolic-ref" command, but that command is supported
by the 1.7 version too, and even older versions.
=> Accept git 1.7.2 as the minimum version

commit.go
=> Improve memory usage in Commit.IsImageFile

repo.go, signature.go
Fix time parsing in `GetLatestCommitTime`, which would fail on days 1-9 of the month (since the date only has one digit, see below output). Also moves the time format to a named constant, since it is used in multiple places.
```
--- FAIL: TestGetLatestCommitTime (0.00s)
Error Trace:    repo_test.go:15
Error:		Received unexpected error:
parsing time "Sat Dec 9 17:17:57 2017 -0800" as "Mon Jan 02 15:04:05 2006 -0700": cannot parse "9 17:17:57 2017 -0800" as "02"
```
=> Fix time parsing

repo_commit.go
The CommitsBefore method is `only` used to retrieve commits for the push webhook if a new branch is pushed.
Namely at https://github.com/go-gitea/gitea/blob/a4cd4616c6f8524f8eb79d6184e855b3a8164130/models/update.go#L229
The refactored method now returns exactly those commits which were added in the new branch and are not existing in any other branch.
This result now behaves exactly as github (compared to the webhook result) except for the order.
The order will be fixed in a separate PR as there is another method which needs order fixing.
All these changes are necessary to implement https://github.com/go-gitea/gitea/pull/2548
=> Refactor CommitsBefore method to match github

commit_info.go, commit_info_test.go
This will be a part of PR to fix go-gitea/gitea#3181
=> Fix retrieve file last commit branchName

repo_pull.go, repo_pull_test.go
=> Add GetFormatPatch receiver for a repository

command.go
=> Set default command execution timeout as changable

repo_pull.go, repo_pull_test.go
=> Use io reader for GetFormatPatch

repo_commit.go
Needed for getting commit ID for hidden refs
=> Make GetRefCommitID exported

parse.go, parse_test.go, tree.go
Fixes the parsing of filenames with escaped characters, which did not previously handled escaped characters such as `\n` correctly. Also adds unit tests.
This PR also exposes the parsing functionality as public, so that it can be reused (see https://github.com/go-gitea/gitea/blob/a89592d4abfef01e68e3c53a3cdb3846b03abd2b/models/repo_indexer.go#L234)
=> Fix tree entry parsing

sha1.go
Some simplifications to prevent wheel re-invention:
- Use `hex.EncodeString(..)` instead of manually hex encoding
- This is likely to be faster, since we don't have to allocate a byte array containg `012..ef` each call.
- Use `copy(..)` instead of manually copying bytes
- This is likely to be faster, since `copy` has architecture-specialized implementations
- Use `bytes.Equal(..)` instead of manually comparing bytes
- Again, this is likely to be faster, since `bytes.Equal` has architecture-specialized implementations
For the record, converting an array to a slice (`arr[:]`) does *not* copy the array.
=> Simplify sha1 functions

commit_test.go, repo_commit.go, repo_commit_test.go, repo_test.go
Targets https://github.com/go-gitea/gitea/issues/3458
Should fix `commitsBefore` for older git versions.
=> fix git version below 2.7

commit.go, commit_test.go
Needed for go-gitea/gitea#4127
=> Add function to resolve short commit ID to full SHA1

command.go
Make an explicit copy of GlobalCommandArgs, otherwise append might overwrite it.
My recent PR for Gitea (https://github.com/go-gitea/gitea/pull/5367) exposed a bug that caused wrong commands to be executed:
```
[...ules/context/repo.go:364 func1()] [E] GetTags: exit status 129 - error: unknown option `sort=-v:refname'
usage: git cat-file (-t [--allow-unknown-type] | -s [--allow-unknown-type] | -e | -p | <type> | --textconv | --filters) [--path=<path>] <object>
```
(`--sort` is an argument for `tag`, not for `cat-file`.)
The problem seems to be that GlobalCommandArgs is changed by append, which triggers this behavior.
=> command: fix NewCommand

tree.go
Fixes the bug described at https://github.com/go-gitea/git/pull/123#issuecomment-452340523
=> Fixed a bug where TreeEntries were getting cached, (thanks @filipnavara)

submodule.go, submodule_test.go
should fix go-gitea/gitea#2775 and replace #108
=> fix submodule has port

commit.go, repo_commit.go
This allows us to get the branch a commit belongs to. 
If commit `oooo` is on `master` and `a_feature_branch`, it defaults to `master` as the result. I have gone through GitHub's implementation and it is the same. Here is an example, https://github.com/go-gitea/gitea/commit/7cb1d8296dbb35fa9b76666fc741bcb129467cd7 exists on `master` and `release/v1.7` but it defaults to showing `master`
Needed to fix https://github.com/go-gitea/gitea/issues/5473
=> get branch commit belongs to

repo_tag.go, repo_tag_test.go
=> fix get tag list

cache.go, commit_info.go, commit_info_test.go
Add a new interface for cache entrypath's last commit info for a special commit's git tree entries.
=> add last commit cache interface

repo_commit.go, repo_tag.go, repo_tag_test.go
This will fix https://github.com/go-gitea/gitea/issues/5585
It seems  
```
git show-ref --tags <tag>
```
will not give the right commit id of this tag, but
```
git rev-list -n 1 $TAG
```
will return the right commit id.
=> fix bug when get tag id

repo_commit.go, repo_commit_test.go
This error message for a bad commitID makes no sense because when the Error object is created, commitID is always empty since NewCommand() call replaced the given commitID. This makes sure we retain the old commitID until after this block.
=> Fix for bad commitID to show up in error

repo_commit.go
Fix panic on signed empty commit message (go-gitea/gitea#6292)
CommitTrees with empty commit messages such as signed tags will panic when trying to parse their commit message. This PR fixes this.
=> Fix panic on signed empty commit message (go-gitea/gitea#6292)

hook.go
This updates the `IsActive` `bool` when doing `Hook.Update`.
(Needed that for a separate PR that adds Git hooks to the Gitea API)
=> Update IsActive on Hook.Update
