go-gitea/git

tree_entry.go

Fix variable name who collides with imported package name

Fix variable name collision with import name

---

hook.go

Change the const variable name from `HOOK_PATH_UPDATE ` to `HookPathUpdate`

Change const variable name

---

sha1.go

Since gitea will reference it.

emptySHA -> EmptySHA

---

MAINTAINERS

update maintainer list for LGTM

---

repo_tag.go

This will be part of PRs to resolve go-gitea/gitea#624

Fix bug in get repo tag infos

---

repo_branch.go

Preparation for go-gitea/gitea#307

Add CreateBranch command

---

hook.go

This is a broken change. It will change the hooks directory structure.

Use a new hooks dir struct

---

repo_tag.go

fix https://github.com/go-gitea/gitea/issues/1664

fix tag contain character ")"

---

README.md

replace gitter chat with discord

---

tree_entry.go

See https://github.com/go-gitea/gitea/issues/2005

Fix bug in GetCommitInfos

---

commit.go

fix commit tree view when submodule file lost

---

.github/issue_template.md

Add discourse link to issue template

---

commit.go

Trim commit message when generating Summary

---

repo_branch.go

Fix branch deletion with git < 2.5.0

---

.github/issue_template.md

This allows users to post an issue, while automatically hiding the help text.

Comment help text for issues

---

tree_entry.go
tree_entry_test.go

Needed to implement natural dir/file sorting in gitea

Add method to allow custom sorting of tree entry list

---

signature.go

Will fix go-gitea/gitea#2763 issue

Fix signature without time parsing to fall back to unix 0 time

---

blob.go

This is a replacement for #47
I need this function for my refactor (related work: https://github.com/go-gitea/git/pull/93, https://github.com/go-gitea/gitea/pull/2990, https://github.com/go-gitea/gitea/issues/2669).

Introduce Blob.DataAsync

---

blob.go
blob_test.go

I accidentally overwrote my `master`, this is exactly the same as #93

Improve memory usage for Blob.Data() by ~50%

---

commit_info.go

Will fix https://github.com/go-gitea/gitea/issues/3242.

Kill zombie subprocesses in GetCommitsInfo

---

.lgtm

update LGTM pattern

---

repo_blame.go

See comments of https://github.com/go-gitea/gitea/pull/3748#issuecomment-389522341

Fix blame problem for older git versions

---

Makefile

fix golint path.

---

commit.go

ref: https://github.com/gogs/gogs/blob/1f11c1f71a314a85ab09b75f10a527a351020144/vendor/github.com/gogs/git-module/commit.go#L267:6

Added commit file status, port from gogs
